blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ DiscusiÃ³n General
    url: https://github.com/Ariel-GonzAguer/codigo-codigo/discussions
    about: Para preguntas generales, ideas y discusiones sobre el proyecto
  - name: ðŸ†˜ Soporte
    url: https://github.com/Ariel-GonzAguer/codigo-codigo/discussions/categories/q-a
    about: Para obtener ayuda con el uso o configuraciÃ³n del proyecto
